--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg120+1)
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ApiUserChargingPoint; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."ApiUserChargingPoint" (
    "ApiUsersUserId" text NOT NULL,
    "ChargingPointsChargingPointID" text NOT NULL
);


ALTER TABLE public."ApiUserChargingPoint" OWNER TO role_admin;

--
-- Name: ChargingPointProviders; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."ChargingPointProviders" (
    "ChargingPointProviderID" integer NOT NULL,
    "ChargingPointProviderName" text NOT NULL
);


ALTER TABLE public."ChargingPointProviders" OWNER TO role_admin;

--
-- Name: ChargingPointProviders_ChargingPointProviderID_seq; Type: SEQUENCE; Schema: public; Owner: role_admin
--

ALTER TABLE public."ChargingPointProviders" ALTER COLUMN "ChargingPointProviderID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ChargingPointProviders_ChargingPointProviderID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ChargingPoints; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."ChargingPoints" (
    "ChargingPointID" text NOT NULL,
    "FacilityID" integer NOT NULL,
    "ChargingPointProviderID" integer NOT NULL,
    "State" text,
    "ChargePointSerialNumber" text,
    "FirmwareVersion" text,
    "ChargePointModel" text
);


ALTER TABLE public."ChargingPoints" OWNER TO role_admin;

--
-- Name: ChargingSchedulePeriods; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."ChargingSchedulePeriods" (
    "ChargingSchedulePeriodId" text NOT NULL,
    "ChargingTransactionId" text NOT NULL,
    "Charging" boolean NOT NULL,
    "StartTime" timestamp with time zone NOT NULL
);


ALTER TABLE public."ChargingSchedulePeriods" OWNER TO role_admin;

--
-- Name: ChargingTransactions; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."ChargingTransactions" (
    "ChargingTransactionID" text NOT NULL,
    "v16Id" integer NOT NULL,
    "ConnectorName" integer NOT NULL,
    "ChargingPointID" text NOT NULL,
    "IdTagID" text NOT NULL,
    "State" text NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL,
    "TotalKWh" double precision,
    "TotalSeconds" integer,
    "TotalPriceEuros" double precision,
    "EvseId" integer,
    "Soc" integer,
    "EffectWatts" integer
);


ALTER TABLE public."ChargingTransactions" OWNER TO role_admin;

--
-- Name: Connectors; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."Connectors" (
    "ConnectorId" integer NOT NULL,
    "ConnectorName" integer NOT NULL,
    "ChargingPointId" text NOT NULL,
    "State" text NOT NULL,
    "EvseId" integer
);


ALTER TABLE public."Connectors" OWNER TO role_admin;

--
-- Name: Connectors_ConnectorId_seq; Type: SEQUENCE; Schema: public; Owner: role_admin
--

ALTER TABLE public."Connectors" ALTER COLUMN "ConnectorId" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Connectors_ConnectorId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Evses; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."Evses" (
    "Id" integer NOT NULL,
    "EvseId" integer NOT NULL,
    "ChargingPointId" text NOT NULL
);


ALTER TABLE public."Evses" OWNER TO role_admin;

--
-- Name: Facilities; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."Facilities" (
    "FacilityID" integer NOT NULL,
    "FacilityName" text NOT NULL,
    "FacilityOwnerID" integer NOT NULL,
    "EnergyZoneName" text NOT NULL,
    "UserId" text NOT NULL
);


ALTER TABLE public."Facilities" OWNER TO role_admin;

--
-- Name: Facilities_FacilityID_seq; Type: SEQUENCE; Schema: public; Owner: role_admin
--

ALTER TABLE public."Facilities" ALTER COLUMN "FacilityID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Facilities_FacilityID_seq"
    START WITH 5
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: FacilityOwners; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."FacilityOwners" (
    "FacilityOwnerId" integer NOT NULL,
    "FacilityOwnerName" text NOT NULL
);


ALTER TABLE public."FacilityOwners" OWNER TO role_admin;

--
-- Name: FacilityOwners_FacilityOwnerId_seq; Type: SEQUENCE; Schema: public; Owner: role_admin
--

ALTER TABLE public."FacilityOwners" ALTER COLUMN "FacilityOwnerId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FacilityOwners_FacilityOwnerId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: IdTags; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."IdTags" (
    "IdTagID" text NOT NULL,
    "UserId" text NOT NULL
);


ALTER TABLE public."IdTags" OWNER TO role_admin;

--
-- Name: MeterValues; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."MeterValues" (
    "MeterValueID" text NOT NULL,
    "ChargingTransactionID" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "ValueRaw" double precision,
    "ValueSignedData" text,
    "Unit" text,
    "Context" text,
    "Location" text,
    "Measurand" text,
    "Phase" text,
    "PriceEuros" double precision
);


ALTER TABLE public."MeterValues" OWNER TO role_admin;

--
-- Name: Reservations; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."Reservations" (
    "ReservationId" integer NOT NULL,
    "ChargingPointId" text NOT NULL,
    "ExpiryDate" timestamp with time zone NOT NULL,
    "IdTagId" text NOT NULL,
    "ConnectorId" integer NOT NULL
);


ALTER TABLE public."Reservations" OWNER TO role_admin;

--
-- Name: Reservations_ReservationId_seq; Type: SEQUENCE; Schema: public; Owner: role_admin
--

ALTER TABLE public."Reservations" ALTER COLUMN "ReservationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reservations_ReservationId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."Users" (
    "UserId" text NOT NULL,
    "HashedPassword" text NOT NULL,
    "Salt" text NOT NULL,
    "Discriminator" character varying(21) NOT NULL,
    "FirstName" text,
    "LastName" text,
    "Email" text,
    "RefreshToken" text,
    "TokenExpiry" timestamp with time zone,
    "IsAdmin" boolean,
    "ChargePointName" text
);


ALTER TABLE public."Users" OWNER TO role_admin;

--
-- Name: Vehicle; Type: TABLE; Schema: public; Owner: role_admin
--

CREATE TABLE public."Vehicle" (
    "VehicleId" integer NOT NULL,
    "VehicleName" text NOT NULL,
    "FacilityOwnerId" integer NOT NULL,
    "VehicleManufacturer" text NOT NULL,
    "IdTagID" text NOT NULL
);


ALTER TABLE public."Vehicle" OWNER TO role_admin;

--
-- Name: Vehicle_VehicleId_seq; Type: SEQUENCE; Schema: public; Owner: role_admin
--

ALTER TABLE public."Vehicle" ALTER COLUMN "VehicleId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Vehicle_VehicleId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ChargingSchedulePeriods ChargingSchedulePeriods_pkey; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ChargingSchedulePeriods"
    ADD CONSTRAINT "ChargingSchedulePeriods_pkey" PRIMARY KEY ("ChargingSchedulePeriodId");


--
-- Name: Evses Evses_pkey; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Evses"
    ADD CONSTRAINT "Evses_pkey" PRIMARY KEY ("Id");


--
-- Name: ApiUserChargingPoint PK_ApiUserChargingPoint; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ApiUserChargingPoint"
    ADD CONSTRAINT "PK_ApiUserChargingPoint" PRIMARY KEY ("ApiUsersUserId", "ChargingPointsChargingPointID");


--
-- Name: ChargingPointProviders PK_ChargingPointProviders; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ChargingPointProviders"
    ADD CONSTRAINT "PK_ChargingPointProviders" PRIMARY KEY ("ChargingPointProviderID");


--
-- Name: ChargingPoints PK_ChargingPoints; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ChargingPoints"
    ADD CONSTRAINT "PK_ChargingPoints" PRIMARY KEY ("ChargingPointID");


--
-- Name: ChargingTransactions PK_ChargingTransactions; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ChargingTransactions"
    ADD CONSTRAINT "PK_ChargingTransactions" PRIMARY KEY ("ChargingTransactionID");


--
-- Name: Connectors PK_Connectors; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Connectors"
    ADD CONSTRAINT "PK_Connectors" PRIMARY KEY ("ConnectorId");


--
-- Name: Facilities PK_Facilities; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Facilities"
    ADD CONSTRAINT "PK_Facilities" PRIMARY KEY ("FacilityID");


--
-- Name: FacilityOwners PK_FacilityOwners; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."FacilityOwners"
    ADD CONSTRAINT "PK_FacilityOwners" PRIMARY KEY ("FacilityOwnerId");


--
-- Name: IdTags PK_IdTags; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."IdTags"
    ADD CONSTRAINT "PK_IdTags" PRIMARY KEY ("IdTagID");


--
-- Name: MeterValues PK_MeterValues; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."MeterValues"
    ADD CONSTRAINT "PK_MeterValues" PRIMARY KEY ("MeterValueID");


--
-- Name: Reservations PK_Reservations; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Reservations"
    ADD CONSTRAINT "PK_Reservations" PRIMARY KEY ("ReservationId");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("UserId");


--
-- Name: Vehicle PK_Vehicle; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Vehicle"
    ADD CONSTRAINT "PK_Vehicle" PRIMARY KEY ("VehicleId");


--
-- Name: Connectors Unique; Type: CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Connectors"
    ADD CONSTRAINT "Unique" UNIQUE ("ConnectorName", "ChargingPointId");


--
-- Name: IX_ApiUserChargingPoint_ChargingPointsChargingPointID; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_ApiUserChargingPoint_ChargingPointsChargingPointID" ON public."ApiUserChargingPoint" USING btree ("ChargingPointsChargingPointID");


--
-- Name: IX_ChargingPoints_ChargingPointProviderID; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_ChargingPoints_ChargingPointProviderID" ON public."ChargingPoints" USING btree ("ChargingPointProviderID");


--
-- Name: IX_ChargingPoints_FacilityID; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_ChargingPoints_FacilityID" ON public."ChargingPoints" USING btree ("FacilityID");


--
-- Name: IX_ChargingTransactions_ConnectorName; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_ChargingTransactions_ConnectorName" ON public."ChargingTransactions" USING btree ("ConnectorName");


--
-- Name: IX_ChargingTransactions_IdTagID; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_ChargingTransactions_IdTagID" ON public."ChargingTransactions" USING btree ("IdTagID");


--
-- Name: IX_Connectors_ChargingPointId; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_Connectors_ChargingPointId" ON public."Connectors" USING btree ("ChargingPointId");


--
-- Name: IX_Facilities_FacilityOwnerID; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_Facilities_FacilityOwnerID" ON public."Facilities" USING btree ("FacilityOwnerID");


--
-- Name: IX_IdTags_UserId; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_IdTags_UserId" ON public."IdTags" USING btree ("UserId");


--
-- Name: IX_MeterValues_ChargingTransactionID; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_MeterValues_ChargingTransactionID" ON public."MeterValues" USING btree ("ChargingTransactionID");


--
-- Name: IX_Reservations_ChargingPointId; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_Reservations_ChargingPointId" ON public."Reservations" USING btree ("ChargingPointId");


--
-- Name: IX_Reservations_IdTagId; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_Reservations_IdTagId" ON public."Reservations" USING btree ("IdTagId");


--
-- Name: IX_Vehicle_FacilityOwnerId; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_Vehicle_FacilityOwnerId" ON public."Vehicle" USING btree ("FacilityOwnerId");


--
-- Name: IX_Vehicle_IdTagID; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "IX_Vehicle_IdTagID" ON public."Vehicle" USING btree ("IdTagID");


--
-- Name: fki_ChargingPoint; Type: INDEX; Schema: public; Owner: role_admin
--

CREATE INDEX "fki_ChargingPoint" ON public."ChargingTransactions" USING btree ("ChargingPointID");


--
-- Name: ChargingTransactions ChargingPoint; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ChargingTransactions"
    ADD CONSTRAINT "ChargingPoint" FOREIGN KEY ("ChargingPointID") REFERENCES public."ChargingPoints"("ChargingPointID") NOT VALID;


--
-- Name: ChargingSchedulePeriods ChargingTransaction; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ChargingSchedulePeriods"
    ADD CONSTRAINT "ChargingTransaction" FOREIGN KEY ("ChargingTransactionId") REFERENCES public."ChargingTransactions"("ChargingTransactionID") NOT VALID;


--
-- Name: Reservations Connectors; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Reservations"
    ADD CONSTRAINT "Connectors" FOREIGN KEY ("ConnectorId") REFERENCES public."Connectors"("ConnectorId") NOT VALID;


--
-- Name: Evses Evses_ChargingPointId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Evses"
    ADD CONSTRAINT "Evses_ChargingPointId_fkey" FOREIGN KEY ("ChargingPointId") REFERENCES public."ChargingPoints"("ChargingPointID") ON UPDATE CASCADE;


--
-- Name: ApiUserChargingPoint FK_ApiUserChargingPoint_ChargingPoints_ChargingPointsChargingP~; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ApiUserChargingPoint"
    ADD CONSTRAINT "FK_ApiUserChargingPoint_ChargingPoints_ChargingPointsChargingP~" FOREIGN KEY ("ChargingPointsChargingPointID") REFERENCES public."ChargingPoints"("ChargingPointID") ON DELETE CASCADE;


--
-- Name: ApiUserChargingPoint FK_ApiUserChargingPoint_Users_ApiUsersUserId; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ApiUserChargingPoint"
    ADD CONSTRAINT "FK_ApiUserChargingPoint_Users_ApiUsersUserId" FOREIGN KEY ("ApiUsersUserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: ChargingPoints FK_ChargingPoints_ChargingPointProviders_ChargingPointProvider~; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ChargingPoints"
    ADD CONSTRAINT "FK_ChargingPoints_ChargingPointProviders_ChargingPointProvider~" FOREIGN KEY ("ChargingPointProviderID") REFERENCES public."ChargingPointProviders"("ChargingPointProviderID") ON DELETE CASCADE;


--
-- Name: ChargingPoints FK_ChargingPoints_Facilities_FacilityID; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ChargingPoints"
    ADD CONSTRAINT "FK_ChargingPoints_Facilities_FacilityID" FOREIGN KEY ("FacilityID") REFERENCES public."Facilities"("FacilityID") ON DELETE CASCADE;


--
-- Name: ChargingTransactions FK_ChargingTransactions_IdTags_IdTagID; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."ChargingTransactions"
    ADD CONSTRAINT "FK_ChargingTransactions_IdTags_IdTagID" FOREIGN KEY ("IdTagID") REFERENCES public."IdTags"("IdTagID") ON DELETE CASCADE;


--
-- Name: Facilities FK_Facilities_FacilityOwners_FacilityOwnerID; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Facilities"
    ADD CONSTRAINT "FK_Facilities_FacilityOwners_FacilityOwnerID" FOREIGN KEY ("FacilityOwnerID") REFERENCES public."FacilityOwners"("FacilityOwnerId") ON DELETE CASCADE;


--
-- Name: Facilities FK_Facilities_Users; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Facilities"
    ADD CONSTRAINT "FK_Facilities_Users" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") NOT VALID;


--
-- Name: IdTags FK_IdTags_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."IdTags"
    ADD CONSTRAINT "FK_IdTags_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: MeterValues FK_MeterValues_ChargingTransactions_ChargingTransactionID; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."MeterValues"
    ADD CONSTRAINT "FK_MeterValues_ChargingTransactions_ChargingTransactionID" FOREIGN KEY ("ChargingTransactionID") REFERENCES public."ChargingTransactions"("ChargingTransactionID") ON DELETE CASCADE;


--
-- Name: Reservations FK_Reservations_ChargingPoints_ChargingPointId; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Reservations"
    ADD CONSTRAINT "FK_Reservations_ChargingPoints_ChargingPointId" FOREIGN KEY ("ChargingPointId") REFERENCES public."ChargingPoints"("ChargingPointID") ON DELETE CASCADE;


--
-- Name: Reservations FK_Reservations_IdTags_IdTagId; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Reservations"
    ADD CONSTRAINT "FK_Reservations_IdTags_IdTagId" FOREIGN KEY ("IdTagId") REFERENCES public."IdTags"("IdTagID") ON DELETE CASCADE;


--
-- Name: Vehicle FK_Vehicle_FacilityOwners_FacilityOwnerId; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Vehicle"
    ADD CONSTRAINT "FK_Vehicle_FacilityOwners_FacilityOwnerId" FOREIGN KEY ("FacilityOwnerId") REFERENCES public."FacilityOwners"("FacilityOwnerId") ON DELETE CASCADE;


--
-- Name: Vehicle FK_Vehicle_IdTags_IdTagID; Type: FK CONSTRAINT; Schema: public; Owner: role_admin
--

ALTER TABLE ONLY public."Vehicle"
    ADD CONSTRAINT "FK_Vehicle_IdTags_IdTagID" FOREIGN KEY ("IdTagID") REFERENCES public."IdTags"("IdTagID") ON DELETE CASCADE;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO role_readonly;
GRANT USAGE ON SCHEMA public TO role_readwrite;
GRANT ALL ON SCHEMA public TO role_admin;


--
-- Name: TABLE "ApiUserChargingPoint"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."ApiUserChargingPoint" TO role_readwrite;
GRANT SELECT ON TABLE public."ApiUserChargingPoint" TO role_readonly;


--
-- Name: TABLE "ChargingPointProviders"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."ChargingPointProviders" TO role_readwrite;
GRANT SELECT ON TABLE public."ChargingPointProviders" TO role_readonly;


--
-- Name: SEQUENCE "ChargingPointProviders_ChargingPointProviderID_seq"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT ALL ON SEQUENCE public."ChargingPointProviders_ChargingPointProviderID_seq" TO role_readwrite;
GRANT SELECT ON SEQUENCE public."ChargingPointProviders_ChargingPointProviderID_seq" TO role_readonly;


--
-- Name: TABLE "ChargingPoints"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."ChargingPoints" TO role_readwrite;
GRANT SELECT ON TABLE public."ChargingPoints" TO role_readonly;


--
-- Name: TABLE "ChargingSchedulePeriods"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."ChargingSchedulePeriods" TO role_readwrite;
GRANT SELECT ON TABLE public."ChargingSchedulePeriods" TO role_readonly;


--
-- Name: TABLE "ChargingTransactions"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."ChargingTransactions" TO role_readwrite;
GRANT SELECT ON TABLE public."ChargingTransactions" TO role_readonly;


--
-- Name: TABLE "Connectors"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."Connectors" TO role_readwrite;
GRANT SELECT ON TABLE public."Connectors" TO role_readonly;


--
-- Name: SEQUENCE "Connectors_ConnectorId_seq"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT ALL ON SEQUENCE public."Connectors_ConnectorId_seq" TO role_readwrite;
GRANT SELECT ON SEQUENCE public."Connectors_ConnectorId_seq" TO role_readonly;


--
-- Name: TABLE "Evses"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."Evses" TO role_readwrite;
GRANT SELECT ON TABLE public."Evses" TO role_readonly;


--
-- Name: TABLE "Facilities"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."Facilities" TO role_readwrite;
GRANT SELECT ON TABLE public."Facilities" TO role_readonly;


--
-- Name: SEQUENCE "Facilities_FacilityID_seq"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT ALL ON SEQUENCE public."Facilities_FacilityID_seq" TO role_readwrite;
GRANT SELECT ON SEQUENCE public."Facilities_FacilityID_seq" TO role_readonly;


--
-- Name: TABLE "FacilityOwners"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."FacilityOwners" TO role_readwrite;
GRANT SELECT ON TABLE public."FacilityOwners" TO role_readonly;


--
-- Name: SEQUENCE "FacilityOwners_FacilityOwnerId_seq"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT ALL ON SEQUENCE public."FacilityOwners_FacilityOwnerId_seq" TO role_readwrite;
GRANT SELECT ON SEQUENCE public."FacilityOwners_FacilityOwnerId_seq" TO role_readonly;


--
-- Name: TABLE "IdTags"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."IdTags" TO role_readwrite;
GRANT SELECT ON TABLE public."IdTags" TO role_readonly;


--
-- Name: TABLE "MeterValues"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."MeterValues" TO role_readwrite;
GRANT SELECT ON TABLE public."MeterValues" TO role_readonly;


--
-- Name: TABLE "Reservations"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."Reservations" TO role_readwrite;
GRANT SELECT ON TABLE public."Reservations" TO role_readonly;


--
-- Name: SEQUENCE "Reservations_ReservationId_seq"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT ALL ON SEQUENCE public."Reservations_ReservationId_seq" TO role_readwrite;
GRANT SELECT ON SEQUENCE public."Reservations_ReservationId_seq" TO role_readonly;


--
-- Name: TABLE "Users"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."Users" TO role_readwrite;
GRANT SELECT ON TABLE public."Users" TO role_readonly;


--
-- Name: TABLE "Vehicle"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE public."Vehicle" TO role_readwrite;
GRANT SELECT ON TABLE public."Vehicle" TO role_readonly;


--
-- Name: SEQUENCE "Vehicle_VehicleId_seq"; Type: ACL; Schema: public; Owner: role_admin
--

GRANT ALL ON SEQUENCE public."Vehicle_VehicleId_seq" TO role_readwrite;
GRANT SELECT ON SEQUENCE public."Vehicle_VehicleId_seq" TO role_readonly;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: role_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE role_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO role_readwrite;
ALTER DEFAULT PRIVILEGES FOR ROLE role_admin IN SCHEMA public GRANT SELECT ON SEQUENCES TO role_readonly;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: role_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE role_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO role_readwrite;
ALTER DEFAULT PRIVILEGES FOR ROLE role_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO role_readonly;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: role_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE role_admin IN SCHEMA public GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLES TO role_readwrite;
ALTER DEFAULT PRIVILEGES FOR ROLE role_admin IN SCHEMA public GRANT SELECT ON TABLES TO role_readonly;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: role_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE role_admin GRANT ALL ON SEQUENCES TO role_readwrite;
ALTER DEFAULT PRIVILEGES FOR ROLE role_admin GRANT SELECT ON SEQUENCES TO role_readonly;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: role_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE role_admin GRANT ALL ON FUNCTIONS TO role_readwrite;
ALTER DEFAULT PRIVILEGES FOR ROLE role_admin GRANT ALL ON FUNCTIONS TO role_readonly;


--
-- Name: DEFAULT PRIVILEGES FOR SCHEMAS; Type: DEFAULT ACL; Schema: -; Owner: role_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE role_admin GRANT USAGE ON SCHEMAS TO role_readwrite;
ALTER DEFAULT PRIVILEGES FOR ROLE role_admin GRANT USAGE ON SCHEMAS TO role_readonly;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: role_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE role_admin GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLES TO role_readwrite;
ALTER DEFAULT PRIVILEGES FOR ROLE role_admin GRANT SELECT ON TABLES TO role_readonly;


--
-- PostgreSQL database dump complete
--

